name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django
        pip install django-cryptography
#         pip install -r requirements.txt
    - name: initialMakeMigrations
      run: python GiftcardSite/manage.py makemigrations LegacySite
    - name: doubleCheck
      run: python GiftcardSite/manage.py makemigrations
    - name: tripleCheck
      run: python GiftcardSite/manage.py migrate
    - name: dbMake
      run: sh GiftcardSite/import_dbs.sh
    - name: Run Tests
      run: |
        python GiftcardSite/manage.py test
